## Two functions to avoid repeat calculation of matrix inverses.
##   cacheSolve(x, ...) only calls solve(x, ...) when the calculation has not 
##      been done before;
##   makeCacheMatrix(x) makes the objects required by cacheSolve.


## makeCacheMatrix generates an object from a matrix which contains the matrix
##    and a cached version of its inverse.
## methods:
##    $set(x) : set the matrix to new contents
##    $get()  : get the content matrix
##    $set_inverse(x) : set the cached version of the inverse of the matrix;
##       (directly calling this is ill-advised!)
##    $get_inverse() : get the cached version of the inverse; NULL if not yet
##       computed
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  set_inverse <- function(inverse) inv <<- inverse
  get_inverse <- function() inv
  list(set = set, get = get,
       set_inverse = set_inverse,
       get_inverse = get_inverse)
}


## cacheSolve takes as argument a cacheMatrix (output generated by 
##    makeCacheMatrix) and calculates its inverse.
## Any additional arguments supplied go to the solve(...) function, but these 
##    only have an effect when the inverse is not called from cache (look for
##    the 'getting cached data' message).
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inv <- x$get_inverse()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data, ...)
  x$set_inverse(inv)
  inv
}
